### ISSUE TITLE
Decide on Python graphics library

### ISSUE THREAD

**Issue by yarbroughw** [cs383-final/cs383-finalproject#1]
[SDL?](https://pypi.python.org/pypi/PySDL2/0.2.0)
[OpenGL?](https://pypi.python.org/pypi/PyOpenGL/3.1.1a1)

**Comment by hawkw** [comment]
I believe OpenGL is much lower-level than SDL. SDL is a library for a wide range of multi-media and interactive applications, while OpenGL is specifically a 3D graphics language. I think SDL applications can include OpenGL graphics.

**Comment by hawkw** [comment]
I think there's also a `graphics` package in the Python standard library, as well. While I have no experience with it, we should definitely check it out. If that's sufficient for our purposes, it would be awesome to not need an external dependency.

**Comment by hawkw** [comment]
Never mind, the tutorial for a `graphics` package I found wasn't from the Python stdlib, it was from an intro to CS course. We probably want an external library for graphics. 

[Pygame](http://pygame.org/news.html) might also be worth a look - we're not making a game, but a lot of its' functionality might be useful.

**Comment by hawkw** [comment]
Closed as 'won't fix'.
