### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by hawkw** [cs383-final/cs383-finalproject#3]
I'd love to set up Travis CI to build each push and PR to this repo, but I need to be a repo admin to enable the hook. Mind making me an admin?

**Comment by yarbroughw** [comment]
Github seems to have a 1-admin-per-repo rule. I'll transfer the repo over to you if you promise to transfer it back :)

**Comment by yarbroughw** [comment]
Or alternatively, we could make an "organization" for this project?

**Comment by yarbroughw** [comment]
Ok, just did the second option. A little silly, but whatever gets the job done.
